version: "3"
services:
  mongodb-practice:
    image: "mongo:6.0.3"
    restart: always
    container_name: mongodb-practice
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: testDb
    volumes:
      - ./data/mongodb:/data/db